### ISSUE TITLE
google graph

### ISSUE THREAD

**Issue by pussimus** [tttapa/ESP8266#1]
Hey 
Could you plz set a like to your google graph code, since i could find it :)

I like your guide alot, its a really well done beginner guide

**Comment by tttapa** [comment]
The files are in the [data folder of the temperature logger example](https://github.com/tttapa/ESP8266/tree/master/Examples/16.%20Data%20logging/A-Temperature_logger/Uncompressed_data).

Glad you liked it!

Pieter
