### ISSUE TITLE
Operation of Reset and Program switches

### ISSUE THREAD

**Issue by minimeccanica** [tttapa/ESP8266#10]
Thank you for the excellent neat guide, the scheme of how to pull up/ground some GPIOs is the first I found clear.
One request: could you specify the operation of the two switches located on reset and GPIO0 during power-on phase? Are they useful during any other phase?'
Thx and compliments again
Manlio

**Comment by tttapa** [comment]
Yes, you need them in the [uploading phase](https://tttapa.github.io/ESP8266/Chap06%20-%20Uploading.html) if your board doesn't have an auto-program circuit.
