### ISSUE TITLE
Example - How to control Relays on multiple ESPs/nodemcu(s) ?

### ISSUE THREAD

**Issue by brian12112** [tttapa/ESP8266#20]
Hello Mr. Tappa. 

Do you have an Example Sketches How to control multiple nodemcu(s) relays using a Ethernet Shield?

My plan is to using Ethernet shield to read inputs/buttons and send to 5 Nodemcu to control 10 relays via router (each node has a 2 relays).

Many Thanks for your Great Libraries...

**Comment by tttapa** [comment]
This is an issue tracker for the guide and examples.

Please us an online forum for help with your project.

**Comment by brian12112** [comment]
okay Mr tttapa. I'll post it on the forum.

**Comment by tttapa** [comment]
What's wrong with the Arduino forum? You could try reddit.

**Comment by brian12112** [comment]
Nothing's wrong with Arduino forum. Just dont have the account yet. I'll Try reddit. Thanks anyway.
