### ISSUE TITLE
Problem with Led Control example

### ISSUE THREAD

**Issue by Primus007** [tttapa/ESP8266#3]
Many thanks for your great work and the examples. They was very helpful for me.

I have a problem with the Led Control example. I use an ESP-01. I have uploaded the Data Dir and the sketch (i use the arduino ide 1.8.2 (win7) for this) . The Server starts:
Station connected to ESP8266 AP
OTA ready

Spiffs all ok 
WebSocket server started.
mDNS responder started: http://esp8266.local
HTTP server started.
handleFileRead: /
	Sent file: /index.html
handleFileRead: /main.css
	Sent file: /main.css
handleFileRead: /WebSocket.js
	Sent file: /WebSocket.js

!!! and here is the Problem. It need 1 Minute an 20 seconds to go to the next step. Before and after this all runs fast. 

[0] Connected from 192.168.4.2 url: /
handleFileRead: /favicon.ico
	Sent file: /favicon.ico
[0] get Text: Connect Wed May 03 2017 15:21:11 GMT+0200 (CEST)
handleFileRead: /favicon-144x144.png
	Sent file: /favicon-144x144.png

when i try 192.168.4.1/edit.html 
is the same problem with the main.css it need over one minute to load.

there is no difference if i use the .js / .css or the .gz files.

i can't connect to http://esp8266.local  I connect to 192.168.4.1

i try to connect with my android smartphone always. i tryed with a iphone but the problem is the same.

Please can you help me to solve the problem?
many thanks.

**Comment by Primus007** [comment]
I have found the solution:
The Problem is the WebSocket.js line number 5: `<link href='https://fonts.googleapis.com/css?family=Roboto:300' rel='stylesheet' type='text/css'>`
It tries to get the font over the web. but i use my esp as AP! Nothing can get from the web!
Now it works fine.

**Comment by tttapa** [comment]
That's a bug indeed, I'll fix it when I find the time.
Thanks for your feedback.

Pieter
