### ISSUE TITLE
Exhaustion of RAM when Client uploads heavy images on webserver(local host)

### ISSUE THREAD

**Issue by acharyanachiket** [tttapa/ESP8266#52]
The RAM of ESP8266 gets exhausted when the client uploads heavy data to the webserver. Is it possible to still upload the heavy images and shift the webserver memory to SPIFFS or PROGMEM instead of RAM

**Comment by tttapa** [comment]
That's quite an advanced topic. I haven't experimented with the ESP8266 in a long time, and I'm quite busy at the moment, so I'm afraid I can't really help you. It would probably be a better idea to contact the developers of the ESP8266 Core, who wrote the web server code.
