### ISSUE TITLE
Needed to add a service before I could get mDNS working

### ISSUE THREAD

**Issue by MProx** [tttapa/ESP8266#57]
Hi, 

At first I couldn't get the mDNS working on my NodeMCU, but I eventually managed to get it running by adding the following line to the beginning of the loop() function:

MDNS.update();

This line is present in the mDNS example sketch, which is how I worked out that I needed it.

Thanks,
M

**Comment by aramperez** [comment]
Out of curiosity, is mDNS working in STA mode, AP mode or both?

Thanks,
Aram

**Comment by MProx** [comment]
I'm using it as a station on my home wifi network. I have not tried the others. I used the exact code from tttapa's tutorial, modifying only the SSID and password. The only way I could get it to work was to invoke MDNS.update() right at the beginning of loop().

**Comment by aramperez** [comment]
I can't get mDNS to work in AP mode :-(.

Thanks!

**Comment by MProx** [comment]
Hmm, does it respond to a ping (either using `esp8266.local` or the IP address)? 

I also found that `MDNS.update();` has to appear before `server.handleClient();` in the `loop` function.

**Comment by aramperez** [comment]
Ok, I have my MDNS.update after server.handleClient. I'll give that a try in the new few days, I'm busy with other stuff right now.

Thanks!
