### ISSUE TITLE
Chapter 12 - A-Upload_files_to_server

### ISSUE THREAD

**Issue by Lena-M** [tttapa/ESP8266#6]
At first i like to thank you for this great tutorial.
In chapter 12 is a reference to "/update.html", but there is no data folder nor a listing of the needed code.
Greetings Lena

**Comment by LZHenry** [comment]
Distinguished Learning Guide... Thank you very much... I also FAILED because this html file is ?missing???? 

Trying to learn, but think this is the reason the example will not operate???
