### ISSUE TITLE
Great article very interesting

### ISSUE THREAD

**Issue by HuibGroenewegen** [tttapa/ESP8266#62]
A lot of information but very usefull. I'm playing around a while with the ESP8266 but the first time I  see a complete guide. I'm looking for a way to load files from an SD card on the ESP8266 to  Node-Red . I was looking first for MQTT but I think the best way is with a webserver based solution on the ESP8266. It will not be easy to understand everything but it is a good piece of work to study around. Thanks a lot for your time and effort

**Comment by tttapa** [comment]
Glad to hear you found it useful :)
