### ISSUE TITLE
Thank you for a well written and professional tutorial!

### ISSUE THREAD

**Issue by kjbrand33** [tttapa/ESP8266#64]
We are training hundreds of teachers at a Computer Science conference @ the University of Indianapolis [Flipping the Switch](https://web.cvent.com/event/b30f2a8e-f31b-449e-8064-0907b5630c88/summary) 

This info will be extremely valuable for several of the sessions we will be presenting.

THANK YOU for such a comprehensive, detailed and annotated resource. We will certainly highlight your contributions at the conference.

Kim

**Comment by tttapa** [comment]
Glad to hear you found it useful :)
