### ISSUE TITLE
Crash during obtaining data

### ISSUE THREAD

**Issue by Sovatna** [tttapa/ESP8266#7]
My NodeMCU got crash while obtaining data. I try to use delay (500), but still problem. please kindly help.

**Comment by tttapa** [comment]
Please keep in mind that this is the issue section for the Beginner's Guide to the ESP8266. If you believe that there is a mistake in the code of the guide, please provide more information (what code did you use, what settings in the IDE etc.)
If you have a problem with your own code, please consider asking it on the [Arduino forum](http://forum.arduino.cc) or Stack Exchange.
